---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  remote_user: vagrant
  # remote_user: user
  sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
